import "./globals.css"
import type { Metadata } from "next"
import { Bellefair, Barlow_Condensed } from "next/font/google"

import clsx from "clsx"
import Navbar from "@/components/nav/Navbar"

const bellefair = Bellefair({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bellefair",
})

const barlowCondensed = Barlow_Condensed({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-barlow-condensed",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={clsx([
          bellefair.variable,
          barlowCondensed.variable,
          "px-6 font-barlow",
        ])}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
